service: image-resize-on-the-fly-functions

custom:
  secrets: ${file(../secrets/secrets.json)}
  # customDomain:
  #   domainName: ${self:custom.secrets.DOMAIN}
  #   basePath: ''
  #   stage: dev
  #   createRoute53Record: true

plugins:
  - serverless-plugin-tracing
  # - serverless-offline
  # - serverless-domain-manager
  # - serverless-graph

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:STAGE, 'dev'}
  profile: serverless-admin
  tracing: true
  region: ${env:REGION, 'us-east-1'}
  environment:
    BUCKET: ${self:custom.secrets.BUCKET}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: "arn:aws:s3:::${self:custom.secrets.BUCKET}"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource: "arn:aws:s3:::${self:custom.secrets.BUCKET}"
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"

functions:
  resize:
    handler: resize.handler
    events:
      - http:
          path: resize/get
          method: get