version: "3"
services:
  image-resize-on-the-fly:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./secrets:/deploy/secrets
    env_file:
      - ./secrets/sls-secrets.env