service: image-resize-on-the-fly

custom:
  secrets: ${file(secrets.json)}
  # customDomain:
  #   domainName: ${self:custom.secrets.DOMAIN}
  #   basePath: ''
  #   stage: dev
  #   createRoute53Record: true

plugins:
  - serverless-plugin-tracing
  # - serverless-offline
  # - serverless-domain-manager
  # - serverless-graph

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:STAGE, 'dev'}
  profile: serverless-admin
  tracing: true
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: "arn:aws:s3:::${self:custom.secrets.BUCKET}"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource: "arn:aws:s3:::${self:custom.secrets.BUCKET}"
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"


  environment:
    BUCKET: ${self:custom.secrets.BUCKET}

functions:
  resize:
    handler: handler.resize
    events:
      - http:
          path: resize/get
          method: get

resources:
  Resources:
    
    ImageResizeOnTheFly:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicReadWrite
        BucketName: ${self:custom.secrets.BUCKET}
        WebsiteConfiguration:
          ErrorDocument: error.html
          IndexDocument: index.html
          RoutingRules:
            - 
              RedirectRule:
                HostName: ${self:custom.secrets.DOMAIN}
                HttpRedirectCode: "307"
                Protocol: "https"
                ReplaceKeyPrefixWith: "${self:provider.stage}/resize/get?key="
              RoutingRuleCondition:
                HttpErrorCodeReturnedEquals: "404"
                KeyPrefixEquals: ""
    
    ImageResizeOnTheFlyPolicy:
      Type: AWS::S3::BucketPolicy
      Properties: 
        Bucket: 
          Ref: ImageResizeOnTheFly
        PolicyDocument: 
          Statement: 
            - 
              Action: 
                - "s3:*"
              Effect: "Allow"
              Resource:
                Fn::Join: 
                  - ""
                  - 
                    - "arn:aws:s3:::"
                    - 
                      Ref: ImageResizeOnTheFly
                    - "/*"
              Principal: "*"